
export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const LOGOUT = 'LOGOUT'

export const TOGGLE_SIDEBAR = 'TOOGLE_SIDEBAR'

export const GET_JOBS_REQUEST = 'GET_JOBS_REQUEST'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'

export const GET_DOSARE_REQUEST = 'GET_DOSARE_REQUEST'
export const GET_DOSARE_SUCCESS = 'GET_DOSARE_SUCCESS'

export const ADD_DOSAR_REQUEST = 'ADD_DOSAR_REQUEST'
export const ADD_DOSAR_SUCCESS = 'ADD_DOSAR_SUCCESS'
export const ADD_DOSAR_FAIL = 'ADD_DOSAR_FAIL'

export const GET_DOSAR_REQUEST = 'GET_DOSAR_REQUEST'
export const GET_DOSAR_SUCCESS = 'GET_DOSAR_SUCCESS'
export const GET_DOSAR_FAIL = 'GET_DOSAR_FAIL'

export const GET_ACTE_REQUEST = 'GET_ACTE_REQUEST'
export const GET_ACTE_SUCCESS = 'GET_ACTE_SUCCESS'

export const GET_ALL_ACTS_REQUEST = 'GET_ALL_ACTS_REQUEST'
export const GET_ALL_ACTS_SUCCESS = 'GET_ALL_ACTS_SUCCESS'
export const GET_ALL_ACTS_FAIL = 'GET_ALL_ACTS_FAIL'

export const ADD_ACT_REQUEST = 'ADD_ACT_REQUEST'
export const ADD_ACT_SUCCESS = 'ADD_ACT_SUCCESS'
export const ADD_ACT_FAIL = 'ADD_ACT_FAIL'

export const DELETE_DOSAR_REQUEST = 'DELETE_DOSAR_REQUEST'
export const DELETE_DOSAR_SUCCESS = 'DELETE_DOSAR_SUCCESS'
export const DELETE_DOSAR_FAIL = 'DELETE_DOSAR_FAIL'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const CHANGE_PAGE = 'CHANGE_PAGE'





